name: Update Submodules and Create PR
on:
  repository_dispatch:
    types: [test-submodules-update]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set Git Config
        run: |
          git config --global user.email "${{ secrets.GH_APP_ID }}+test-pull-gabr[bot]@users.noreply.github.com"
          git config --global user.name "test-pull-gabr[bot]"

      - name: Update Submodule to the Latest Commit on Master
        run: |
          git checkout main
          git reset --hard origin/main
          git submodule update --recursive
          git add test-sub
          git commit -m "Update submodule to latest commit on main" || echo "No changes to commit"

      - name: Get token
        id: get_app_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.GH_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.get_app_token.outputs.token }}
          base: main
          branch: "update-submodule"
          title: "Update submodule to the latest version"
          body: "This PR updates the submodule to the latest version."
          commit-message: "Update submodule to the latest commit"
