name: Update Submodules and Create PR
on:
  repository_dispatch:
    types: [test-submodules-update]
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write

jobs:
  update-submodules:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set Git Config
        run: |
          git config --global user.email "gnevas70@gmail.com"
          git config --global user.name "gabrielaTest"

      - name: Update Submodule
        run: |
          git submodule update --init --recursive
          cd test-sub
          git fetch origin
          git merge origin/main || git merge --allow-unrelated-histories origin/main || true
          git add .
          git commit -m "Update submodule to latest commit" || echo "No changes to commit in submodule"
          cd ..
          git add test-sub
          git commit -m "Update submodule reference" || echo "No changes to submodule reference"

      - name: Get token
        id: get_app_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.GH_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          permissions: "pull-requests:write"
      
      - name: Push Changes and Create Pull Request
        run: |
          git checkout -b update-submodule-$(date +%s)
          git push origin HEAD
          git push --set-upstream origin HEAD
          gh pr create --title "Update submodule" --body "This PR updates the submodule to the latest commit." --base master
        env:
          GH_TOKEN: ${{ steps.get_app_token.outputs.token }}
