name: Update Submodules and Create PR
on:
  repository_dispatch:
    types: [test-submodules-update]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set Git Config
        run: |
          git config --global user.email "gnevas70@gmail.com"
          git config --global user.name "gabrielaTest"

      - name: Update Submodule
        run: |
          # Deinitialize the submodule in case of unrelated histories
          git submodule deinit -f test-sub
          
          # Remove the submodule directory to ensure it's clean
          rm -rf test-sub
          
          # Reinitialize the submodule and update it to the latest commit
          git submodule update --init --remote --merge test-sub
          
          # Add the submodule changes to the index
          git add test-sub
          
          # Commit the changes, if there are any, otherwise echo a message
          git commit -m "Update submodule to latest commit" || echo "No changes to commit"

      - name: Get token
        id: get_app_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.GH_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.get_app_token.outputs.token }}
          base: main
          branch: "update-submodule"
          title: "Update submodule to the latest version"
          body: "This PR updates the submodule to the latest version."
          commit-message: "Update submodule to the latest commit"
