name: Update Submodules and Create PR
on:
  repository_dispatch:
    types: [test-submodules-update]
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write

jobs:
  update-submodules:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set Git Config
        run: |
          git config --global user.email "gnevas70@gmail.com"
          git config --global user.name "gabrielaTest"

      - name: Update Submodule
        run: |
          git submodule update --init --recursive
          cd test-sub
          git fetch origin
          git merge origin/main || git merge --allow-unrelated-histories origin/main || true
          git add .
          git commit -m "Update submodule to latest commit" || echo "No changes to commit in submodule"
          cd ..
          git add test-sub
          git commit -m "Update submodule reference" || echo "No changes to submodule reference"

      - name: Get token
        id: get_app_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.GH_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          
      - name: Create commits
        run: |
          date +%s > report.txt
          git commit -am "Modify tracked file during workflow"
          date +%s > new-report.txt
          git add -A
          git commit -m "Add untracked file during workflow"
      - name: Uncommitted change
        run: date +%s > report.txt
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ env.branch_name }}
          title: "Update submodule to the latest version"
          body: "This PR updates the submodule to the latest version."
          commit-message: "Update submodule to the latest commit"
