name: Update Submodules and Create PR
on:
  repository_dispatch:
    types: [test-submodules-update]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: Set Git Config
        run: |
          git config --global user.email "${{ secrets.GH_APP_ID }}+test-pull-gabr[bot]@users.noreply.github.com"
          git config --global user.name "test-pull-gabr[bot]"
          
      - name: Create or Checkout Branch
        run: |
          if git rev-parse --verify update-submodules; then
            git checkout update-submodules
            git pull origin update-submodules
          else
            git checkout -b update-submodules
          fi

      - name: Initialize and Update Submodule
        run: |
          git submodule update --recursive
          cd test-sub
          git checkout main
          git reset --hard origin/main
          git pull
          cd ..
          git add test-sub
          git commit -m "Update submodule to latest commit on main" || echo "No changes to commit"

      - name: Push Changes
        id: push-changes
        run: |
          git pull origin update-submodules || echo "No changes to push"
          git push origin update-submodules || echo "No changes to push"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for Existing PR
        id: check-pr
        run: |
          gh pr list --head update-submodules --base main --json number --jq '.[0].number' > pr_number.txt
          PR_NUMBER=$(cat pr_number.txt)
          if [ -z "$PR_NUMBER" ]; then
            echo "No existing PR found"
            echo "pr_exists=false" >> $GITHUB_ENV
          else
            echo "Existing PR found: $PR_NUMBER"
            echo "pr_exists=true" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        run: gh pr create -B main -H update-submodules --title 'Merge update-submodules into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
