name: Update Submodules and Create PR
on:
  repository_dispatch:
    types: [test-submodules-update]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set Git Config
        run: |
          git config --global user.email "${{ secrets.GH_APP_ID }}+test-pull-gabr[bot]@users.noreply.github.com"
          git config --global user.name "test-pull-gabr[bot]"

      - name: Create and Checkout New Branch
        run: |
          git pull
          git checkout -b update-submodules

      - name: Clean Submodule Directory
        run: |
          rm -rf test-sub

      - name: Update Submodule to the Latest Commit on Main
        run: |
          git submodule update --init --recursive
          cd test-sub
          git fetch
          git checkout main
          git reset --hard origin/main
          cd ..
          git add test-sub
          git commit -m "Update submodule to latest commit on main" || echo "No changes to commit"

      - name: Push Changes
        id: push-changes
        run: |
          git pull origin update-submodules || echo "No changes to pull"
          git push origin update-submodules || echo "No changes to push"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        if: steps.push-changes.outcome == 'success'
        run: gh pr create -B main -H update-submodules --title 'Merge update-submodules into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
