name: Update Submodules and Create PR
on:
  repository_dispatch:
    types: [test-submodules-update]
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write

jobs:
  update-submodules:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set Git Config
        run: |
          git config --global user.email "gnevas70@gmail.com"
          git config --global user.name "gabrielaTest"

      - name: Update Submodule
        run: |
          git submodule deinit -f -- test-sub
          git submodule update --init --recursive
          cd test-sub
          git fetch origin
          git merge origin/main || git merge --allow-unrelated-histories origin/main || true
          cd ..
          git add test-sub
          git commit -m "Update submodule to latest commit" || echo "No changes to commit"

      - name: Check for Merge Conflicts
        id: check_conflicts
        run: |
          if git ls-files -u | grep -q '^[^ ]'; then
            echo "conflicts=true" >> $GITHUB_ENV
          else
            echo "conflicts=false" >> $GITHUB_ENV
          fi

      - name: Resolve Merge Conflicts
        if: env.conflicts == 'true'
        run: |
          git merge --abort || true
          git reset --hard
          git submodule update --remote --merge
          git add test-sub
          git commit -m "Resolve merge conflicts in submodule" || echo "No changes to commit"

      - name: Ensure Submodule Changes are Staged
        run: |
          git submodule foreach --recursive 'git add -A'
          git add test-sub
          git commit -m "Ensure submodule changes are staged" || echo "No changes to commit"

      - name: List Submodule Status
        run: |
          git submodule status
          git status
          git diff

      - name: Create Unique Branch Name
        id: create_branch
        run: echo "branch_name=update-submodule-$(date +%s)" >> $GITHUB_ENV

      - name: Push Changes
        run: |
          git checkout -b ${{ env.branch_name }}
          git push origin ${{ env.branch_name }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          branch: ${{ env.branch_name }}
          title: "Update submodule to the latest version"
          body: "This PR updates the submodule to the latest version."
          commit-message: "Update submodule to the latest commit"
