name: Update Submodules and Create PR

on:
  repository_dispatch:
    types: [test-submodules-update]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-submodules:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set Git Config
        run: |
          git config --global user.email "gnevas70@gmail.com"
          git config --global user.name "gabrielaTest"

      - name: Update Submodule
        run: |
          git submodule deinit -f -- test-sub
          git submodule update --init --recursive
          cd test-sub
          git fetch origin
          git merge origin/main || git merge --allow-unrelated-histories origin/main
          cd ..
          git add test-sub
          git commit -m "Update submodule to latest commit" || echo "No changes to commit"
          
      - name: Resolve Merge Conflicts
        if: failure()
        run: |
          git merge --abort
          git reset --hard
          git submodule update --remote --merge
          git add test-sub
          git commit -m "Resolve merge conflicts in submodule" || echo "No changes to commit"

      - name: Create Unique Branch Name
        id: create_branch
        run: echo "branch_name=update-submodule-$(date +%s)" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          branch: ${{ env.branch_name }}
          title: "Update submodule to the latest version"
          body: "This PR updates the submodule to the latest version."
          commit-message: "Update submodule to the latest commit"
